# Generated by Django 3.0.6 on 2020-12-25 03:20

import autoslug.fields
import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201215_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', slugify=core.models.custom_slugify, unique_with=('created_at__month',)),
            preserve_default=False,
        ),
    ]
