# Generated by Django 3.0.6 on 2020-11-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='core.Region'),
        ),
    ]
