# Generated by Django 3.0.6 on 2021-01-02 18:13

import autoslug.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210103_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=core.models.custom_slugify, unique_with=('created_at__month',)),
        ),
    ]
