# Generated by Django 3.0.6 on 2021-01-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
