# Generated by Django 3.0.6 on 2020-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201113_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='bath',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='bed',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='garage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
