# Generated by Django 3.0.6 on 2020-11-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201114_0642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
