# Generated by Django 3.0.6 on 2020-12-14 15:42

import autoslug.fields
import cars.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=cars.models.custom_slugify, unique_with=('created_at__month',))),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=cars.models.custom_slugify, unique_with=('created_at__month',))),
                ('region', models.CharField(blank=True, choices=[('ashanti', 'Ashanti'), ('ahafo', 'Ahafo'), ('brong-ahafo', 'Brong Ahafo'), ('bono-east', 'Bono East '), ('central', 'Central'), ('eastern', 'Eastern'), ('greater-accra', 'Greater Accra'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('north-east', 'North East'), ('upper-east', 'Upper East'), ('upper-west', 'Upper West'), ('volta', 'Volta'), ('oti', 'Oti Region'), ('werstern', 'Western'), ('werstern-north', 'Western North')], max_length=20, null=True)),
                ('int_color', models.CharField(blank=True, max_length=200, null=True)),
                ('ext_color', models.CharField(blank=True, max_length=200, null=True)),
                ('mileage', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas', 'Gas')], max_length=6, null=True)),
                ('gearbox', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=10, null=True)),
                ('drive_type', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True)),
                ('car_state', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=4, null=True)),
                ('engine', models.CharField(blank=True, max_length=200, null=True)),
                ('air_con', models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], max_length=3, null=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), cars.models.max_value_current_year], verbose_name='year')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbrands', to='cars.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=cars.models.custom_slugify, unique_with=('created_at__month',))),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carimages', to='cars.Car')),
            ],
        ),
    ]
