# Generated by Django 3.0.6 on 2020-12-11 12:49

import autoslug.fields
import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=cars.models.custom_slugify, unique_with=('created_at__month',))),
                ('int_color', models.CharField(blank=True, max_length=200, null=True)),
                ('ext_color', models.CharField(blank=True, max_length=200, null=True)),
                ('millage', models.CharField(blank=True, max_length=200, null=True)),
                ('body_type', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=200, null=True)),
                ('drive_type', models.CharField(blank=True, max_length=200, null=True)),
                ('car_state', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=4, null=True)),
                ('engine', models.CharField(blank=True, max_length=200, null=True)),
                ('air_con', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
