# Generated by Django 3.0.6 on 2020-12-14 15:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_delete_carstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='int_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
