# Generated by Django 3.0.6 on 2020-12-11 16:02

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201211_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2012, validators=[django.core.validators.MinValueValidator(1984), cars.models.max_value_current_year], verbose_name='year'),
            preserve_default=False,
        ),
    ]
