# Generated by Django 3.0.6 on 2020-12-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartypes', to='cars.Type'),
        ),
    ]
