# Generated by Django 3.0.6 on 2020-12-14 16:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201214_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ext_color',
            field=colorfield.fields.ColorField(default='#FFF000', max_length=18),
        ),
    ]
