# Generated by Django 3.0.6 on 2020-12-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201211_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'petrol'), ('diesel', 'Diesel'), ('gas', 'Gas')], max_length=6, null=True),
        ),
    ]
