# Generated by Django 3.0.6 on 2020-12-15 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cars', '0003_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carlocality', to='core.Locality'),
        ),
    ]
