# Generated by Django 3.0.6 on 2020-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='featured',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
