# Generated by Django 3.0.6 on 2020-12-14 16:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201214_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ext_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='car',
            name='int_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
