# Generated by Django 3.0.6 on 2020-12-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201212_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carimages', to='cars.Car')),
            ],
        ),
    ]
