# Generated by Django 3.0.6 on 2020-12-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201212_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='millage',
            new_name='mileage',
        ),
    ]
