# Generated by Django 3.0.6 on 2020-12-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20201215_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='state',
            new_name='condition',
        ),
    ]
