# Generated by Django 3.0.6 on 2020-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20201212_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air_con',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], max_length=3, null=True),
        ),
    ]
