# Generated by Django 3.0.6 on 2020-12-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20201222_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpareImage',
            new_name='Sparemage',
        ),
    ]
