# Generated by Django 3.0.6 on 2020-12-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_schoolimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolimage',
            name='sparepart',
        ),
        migrations.AddField(
            model_name='schoolimage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schooltmages', to='cars.School'),
        ),
    ]
