# Generated by Django 3.0.6 on 2020-12-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20201222_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolimage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schooltmage', to='cars.School'),
        ),
    ]
