# Generated by Django 3.0.6 on 2021-01-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
