# Generated by Django 3.0.6 on 2021-01-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking'),
        ('cars', '0017_brand_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotelsparepart', to='core.Booking')),
                ('sparepart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booksparepart', to='cars.SparePart')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotelschool', to='core.Booking')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookschool', to='cars.School')),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotelcar', to='core.Booking')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookcar', to='cars.Car')),
            ],
        ),
    ]
