# Generated by Django 3.0.6 on 2021-01-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_read'),
        ('cars', '0018_carbooking_schoolbooking_sparepartbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingcar', to='core.Booking'),
        ),
        migrations.AlterField(
            model_name='schoolbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingschool', to='core.Booking'),
        ),
        migrations.AlterField(
            model_name='sparepartbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingsparepart', to='core.Booking'),
        ),
    ]
