# Generated by Django 3.0.6 on 2021-01-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_read'),
        ('cars', '0019_auto_20210105_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbooking', to='core.Booking'),
        ),
        migrations.AlterField(
            model_name='schoolbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolbooking', to='core.Booking'),
        ),
        migrations.AlterField(
            model_name='sparepartbooking',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sparepartbooking', to='core.Booking'),
        ),
    ]
