# Generated by Django 3.0.6 on 2021-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_carbooking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbooking',
            name='category',
            field=models.CharField(default='Driving School', max_length=15),
        ),
        migrations.AddField(
            model_name='sparepartbooking',
            name='category',
            field=models.CharField(default='Spare Parts', max_length=15),
        ),
    ]
