# Generated by Django 3.0.6 on 2020-12-24 23:50

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', slugify=property.models.custom_slugify, unique_with=('created_at__month',)),
            preserve_default=False,
        ),
    ]
