# Generated by Django 3.0.6 on 2020-12-04 08:09

import autoslug.fields
from django.db import migrations
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=property.models.custom_slugify, unique_with=('created_at__month',)),
        ),
    ]
