# Generated by Django 3.0.6 on 2020-11-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201113_1344'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='core.Region'),
        ),
    ]
