# Generated by Django 3.0.6 on 2020-12-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20201204_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='property/'),
        ),
    ]
