# Generated by Django 3.0.6 on 2020-12-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201215_0344'),
        ('property', '0002_auto_20201225_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseproperty',
            name='locality',
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality'),
        ),
    ]
