# Generated by Django 3.0.6 on 2020-11-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201113_1344'),
        ('property', '0002_land_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='core.Category'),
        ),
    ]
