# Generated by Django 3.0.6 on 2020-12-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20201224_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landproperty',
            name='locality',
        ),
    ]
