# Generated by Django 3.0.6 on 2020-11-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_land_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='purpose',
            field=models.CharField(choices=[('S', 'sale'), ('R', 'rent')], default='S', max_length=2),
        ),
    ]
