# Generated by Django 3.0.6 on 2020-11-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_land_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='Dimensions',
            new_name='dimension',
        ),
    ]
