# Generated by Django 3.0.6 on 2020-11-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-id']},
        ),
    ]
