# Generated by Django 3.0.6 on 2020-11-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201113_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='purpose',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], default='sale', max_length=4),
        ),
    ]
