# Generated by Django 3.0.6 on 2020-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201204_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carproperty',
            old_name='color',
            new_name='air_con',
        ),
        migrations.AddField(
            model_name='carproperty',
            name='body_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='car_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='drive_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='engine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='ext_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='int_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='millage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carproperty',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
