# Generated by Django 3.0.6 on 2020-12-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_realestate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.RealEstate'),
        ),
    ]
