# Generated by Django 3.0.6 on 2020-12-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realestates', to='property.RealEstate'),
        ),
    ]
