# Generated by Django 3.0.6 on 2020-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20201114_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Land',
        ),
    ]
