# Generated by Django 3.0.6 on 2020-11-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20201117_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='timestamp',
            new_name='date',
        ),
    ]
