# Generated by Django 3.0.6 on 2020-12-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_realestateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandle',
            name='realestate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.RealEstate'),
        ),
    ]
