# Generated by Django 3.0.6 on 2020-11-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201120_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='date',
            new_name='created_at',
        ),
    ]
