# Generated by Django 3.0.6 on 2020-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201226_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
