# Generated by Django 3.0.6 on 2020-11-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locality'),
        ('property', '0012_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('purpose', models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], default='sale', max_length=4)),
                ('bed', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('from_price', models.FloatField()),
                ('to_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Category')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality')),
            ],
        ),
    ]
