# Generated by Django 3.0.6 on 2020-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20201226_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='logo',
            field=models.ImageField(null=True, upload_to='realeastate/logo'),
        ),
    ]
