# Generated by Django 3.0.6 on 2020-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20201120_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='from_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='to_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
