# Generated by Django 3.0.6 on 2020-12-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
