# Generated by Django 3.0.6 on 2020-12-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_property_negotiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='negotiable',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
