# Generated by Django 3.0.6 on 2020-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20201120_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
