# Generated by Django 3.0.6 on 2020-12-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20201226_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='negotiable',
            new_name='price_negotiable',
        ),
    ]
