# Generated by Django 3.0.6 on 2020-11-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locality'),
        ('property', '0021_auto_20201121_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.Region'),
        ),
    ]
