# Generated by Django 3.0.6 on 2020-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20201121_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
