# Generated by Django 3.0.6 on 2020-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20201226_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='location_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
