# Generated by Django 3.0.6 on 2020-12-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_realestate_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialhandle',
            name='realestate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialhandle', to='property.RealEstate'),
        ),
    ]
