# Generated by Django 3.0.6 on 2020-12-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_locality_region'),
        ('property', '0024_auto_20201123_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bath',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='property',
            name='region',
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='LandProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('dimension', models.CharField(blank=True, max_length=200, null=True)),
                ('bed', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('bath', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('garage', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landproperty', to='property.Property')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landproperty', to='core.Region')),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carproperty', to='property.Property')),
            ],
        ),
    ]
