# Generated by Django 3.0.6 on 2020-12-29 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20201228_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realestate', to='property.RealEstate'),
        ),
    ]
