# Generated by Django 3.0.6 on 2020-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20201130_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='purpose',
            field=models.CharField(choices=[('sale', 'for sale'), ('rent', 'for rent')], default='sale', max_length=4),
        ),
    ]
