# Generated by Django 3.0.6 on 2020-12-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_remove_houseproperty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseproperty',
            name='ameneties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
