# Generated by Django 3.0.6 on 2020-12-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_houseproperty_ameneties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseproperty',
            old_name='ameneties',
            new_name='amenities',
        ),
    ]
