# Generated by Django 3.0.6 on 2021-01-01 13:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201226_0700'),
        ('property', '0030_houseproperty_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('purpose', models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], default='sale', max_length=4)),
                ('location_address', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(choices=[('ashanti', 'Ashanti'), ('ahafo', 'Ahafo'), ('brong-ahafo', 'Brong Ahafo'), ('bono-east', 'Bono East '), ('central', 'Central'), ('eastern', 'Eastern'), ('greater-accra', 'Greater Accra'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('north-east', 'North East'), ('upper-east', 'Upper East'), ('upper-west', 'Upper West'), ('volta', 'Volta'), ('oti', 'Oti Region'), ('werstern', 'Western'), ('werstern-north', 'Western North')], max_length=20, null=True)),
                ('image', models.ImageField(upload_to='property/')),
                ('description', models.TextField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=property.models.custom_slugify, unique_with=('created_at__month',))),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Locality')),
            ],
        ),
    ]
