# Generated by Django 3.0.6 on 2021-01-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_auto_20210101_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True),
        ),
    ]
