# Generated by Django 3.0.6 on 2021-01-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking'),
        ('property', '0046_realestatebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotelroombooking', to='core.Booking')),
                ('hotelroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookhotelroom', to='property.HotelRoom')),
            ],
        ),
    ]
