# Generated by Django 3.0.6 on 2021-01-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_hotelroombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatebooking',
            name='category',
            field=models.CharField(default='Real Estate', max_length=15),
        ),
    ]
