# Generated by Django 3.0.6 on 2021-01-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_realestatebooking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroombooking',
            name='category',
            field=models.CharField(default='Hotel Room', max_length=15),
        ),
    ]
