# Generated by Django 3.0.6 on 2021-01-05 20:11

import autoslug.fields
from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_hotelroombooking_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=property.models.custom_slugify, unique_with=('created_at__month',))),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
