# Generated by Django 3.0.6 on 2021-01-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0050_hospitalitycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.HospitalityCategory'),
        ),
    ]
