# Generated by Django 3.0.6 on 2021-01-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_hotel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
    ]
