# Generated by Django 3.0.6 on 2021-01-09 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroombooking',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroombooking',
            name='check_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
