# Generated by Django 3.0.6 on 2021-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0057_auto_20210109_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroombooking',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroombooking',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
